version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/unzip_artifact.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/mount_filesystem.sh
      timeout: 300
      runas: root
