version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/unpack.sh
      timeout: 300
      runas: root
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
